openapi: 3.0.1
info:
  title: NCMP to CPS Proxy API
  description: NCMP to CPS Proxy API
  version: "1.0"
servers:
  - url: /ncmp
paths:
  /v1/ch/{cm-handle}/data/ds/ncmp-datastore:passthrough-operational:
    get:
      tags:
        - network-cm-proxy
      summary: Get resource data from pass-through operational for cm handle
      description: Get resource data from pass-through operational for given cm handle
      operationId: getResourceDataOperationalForCmHandle
      parameters:
        - name: cm-handle
          in: path
          description: "The identifier for a network function, network element, subnetwork\
          \ or any other cm object by managed Network CM Proxy"
          required: true
          schema:
            type: string
        - name: resourceIdentifier
          in: query
          description: The format of resource identifier depend on the associated DMI
            Plugin implementation. For ONAP DMI Plugin it will be RESTConf paths but
            it can really be anything.
          required: true
          allowReserved: true
          schema:
            type: string
          examples:
            sample1:
              value:
                resourceIdentifier: \parent\child
            sample2:
              value:
                resourceIdentifier: "\\parent\\listElement[key=value]"
            sample3:
              value:
                resourceIdentifier: "\\parent\\listElement[key=value]\\grandChild"
            sample4:
              value:
                resourceIdentifier: "parent=1,child=abc"
        - name: Accept
          in: header
          description: "Accept parameter for response, if accept parameter is null,\
          \ that means client can accept any format."
          required: false
          schema:
            type: string
            enum:
              - application/json
              - application/yang-data+json
        - name: options
          in: query
          description: "options parameter in query, it is mandatory to wrap key(s)=value(s)\
          \ in parenthesis'()'."
          required: false
          allowReserved: true
          schema:
            type: string
          examples:
            sample1:
              value:
                options: "(key1=value1,key2=value2)"
            sample2:
              value:
                options: "(key1=value1,key2=value1/value2)"
            sample3:
              value:
                options: "(key1=10,key2=value2,key3=[val31;val32])"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /v1/ch/{cm-handle}/data/ds/ncmp-datastore:passthrough-running:
    get:
      tags:
        - network-cm-proxy
      summary: Get resource data from pass-through running for cm handle
      description: Get resource data from pass-through running for given cm handle
      operationId: getResourceDataRunningForCmHandle
      parameters:
        - name: cm-handle
          in: path
          description: "The identifier for a network function, network element, subnetwork\
          \ or any other cm object by managed Network CM Proxy"
          required: true
          schema:
            type: string
        - name: resourceIdentifier
          in: query
          description: The format of resource identifier depend on the associated DMI
            Plugin implementation. For ONAP DMI Plugin it will be RESTConf paths but
            it can really be anything.
          required: true
          allowReserved: true
          schema:
            type: string
          examples:
            sample1:
              value:
                resourceIdentifier: \parent\child
            sample2:
              value:
                resourceIdentifier: "\\parent\\listElement[key=value]"
            sample3:
              value:
                resourceIdentifier: "\\parent\\listElement[key=value]\\grandChild"
            sample4:
              value:
                resourceIdentifier: "parent=1,child=abc"
        - name: Accept
          in: header
          description: "Accept parameter for response, if accept parameter is null,\
          \ that means client can accept any format."
          required: false
          schema:
            type: string
            enum:
              - application/json
              - application/yang-data+json
        - name: options
          in: query
          description: "options parameter in query, it is mandatory to wrap key(s)=value(s)\
          \ in parenthesis'()'."
          required: false
          allowReserved: true
          schema:
            type: string
          examples:
            sample1:
              value:
                options: "(key1=value1,key2=value2)"
            sample2:
              value:
                options: "(key1=value1,key2=value1/value2)"
            sample3:
              value:
                options: "(key1=10,key2=value2,key3=[val31;val32])"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    post:
      tags:
        - network-cm-proxy
      summary: create resource data from pass-through running for cm handle
      description: create resource data from pass-through running for given cm handle
      operationId: createResourceDataRunningForCmHandle
      parameters:
        - name: cm-handle
          in: path
          description: "The identifier for a network function, network element, subnetwork\
          \ or any other cm object by managed Network CM Proxy"
          required: true
          schema:
            type: string
        - name: resourceIdentifier
          in: query
          description: The format of resource identifier depend on the associated DMI
            Plugin implementation. For ONAP DMI Plugin it will be RESTConf paths but
            it can really be anything.
          required: true
          allowReserved: true
          schema:
            type: string
          examples:
            sample1:
              value:
                resourceIdentifier: \parent\child
            sample2:
              value:
                resourceIdentifier: "\\parent\\listElement[key=value]"
            sample3:
              value:
                resourceIdentifier: "\\parent\\listElement[key=value]\\grandChild"
            sample4:
              value:
                resourceIdentifier: "parent=1,child=abc"
        - name: Content-Type
          in: header
          description: "Content parameter for request, if content parameter is null,\
          \ default value is application/json."
          required: false
          schema:
            type: string
            default: application/json
      requestBody:
        content:
          application/json:
            schema:
              type: string
          application/yang-data+json:
            schema:
              type: string
        required: true
      responses:
        "201":
          description: Created
          content: {}
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /v1/ch/{cm-handle}/modules:
    get:
      tags:
        - network-cm-proxy
      summary: Fetch all module references (name and revision) for a given cm handle
      description: fetch all module references (name and revision) for a given cm
        handle
      operationId: getModuleReferencesByCmHandle
      parameters:
        - name: cm-handle
          in: path
          description: "The identifier for a network function, network element, subnetwork\
          \ or any other cm object by managed Network CM Proxy"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    ErrorMessage:
      title: Error
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        details:
          type: string
