{
 "title": "Inventory REST Interfaces",
 "tags": [
  "lcm-state",
  "inventory",
  "ncmp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "All LCM States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cps_ncmp_inventory_cm_handles_by_state{instance=\"$Instance\", job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inventory API calls by URI and STATUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$Instance\", job=\"$Job\", status=~\"201|200\", uri=\"/ncmpInventory/v1/ch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out of Memory Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum({error=\"OutOfMemoryError\", instance=\"$Instance\", job=\"$Job\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}