{
 "title": "LCM State",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "All LCM States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cmHandlesByState{instance=\"$Instance\", job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ADVISED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cmHandlesByState{state=\"ADVISED\", instance=\"$Instance\", job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "READY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "cmHandlesByState{state=\"READY\", instance=\"$Instance\", job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOCKED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "cmHandlesByState{state=\"LOCKED\", instance=\"$Instance\", job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETING",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "cmHandlesByState{state=\"DELETING\", instance=\"$Instance\", job=\"$Job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}