spring.application.name=cps-ncmp-mcp-server
server.port=8085

# MCP server config
spring.ai.mcp.server.name=cps-ncmp-mcp-server
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.sse-message-endpoint=/mcp/message

# CPS NCMP base URL
cps.base-url=http://localhost:8883
