apiVersion: v1
kind: Service
metadata:
  name: cps-{{ include "cps-and-ncmp.name" . }}-hazelcast
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: cps-and-ncmp
spec:
  clusterIP: None
  selector:
    app: {{ include "cps-and-ncmp.name" . }}
    component: cps
  ports:
    - port: 5701
      targetPort: 5701
      protocol: TCP
      name: hazelcast-port
