apiVersion: v1
kind: Service
metadata:
  name: {{ include "cps-and-ncmp.name" . }}-cps-hazelcast
spec:
  clusterIP: None
  selector:
    app: {{ include "cps-and-ncmp.name" . }}
    component: cps
  ports:
    - port: 5701
      targetPort: 5701
      protocol: TCP
      name: hazelcast-port
