#  ============LICENSE_START=======================================================
#  Copyright (C) 2025-2026 OpenInfra Foundation Europe. All rights reserved.
#  ================================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#  ============LICENSE_END=========================================================

# Reference : https://raw.githubusercontent.com/hazelcast/hazelcast/master/kubernetes-rbac.yaml
# Simplified kubernetes-rbac.yaml with minimum necessary permissions granted to pods to query Kubernetes API.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cps-hazelcast-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: hazelcast
  annotations:
    description: "Hazelcast discovery via Kubernetes API to find cluster members - minimal RBAC"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cps-hazelcast-role
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: hazelcast
rules:
  - apiGroups:
      - ""  # core API group (pods, nodes, services, endpoints)
    resources:
      - endpoints # used to discover other hazelcast members using kubernetes services
      - pods
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices # (for newer kubernetes versions) used to discover other hazelcast members using kubernetes services
    verbs:
      - get
      - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cps-hazelcast-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cps-hazelcast-role
subjects:
  - kind: ServiceAccount
    name: cps-hazelcast-service-account
    namespace: {{ .Release.Namespace }}