apiVersion: v1
kind: Service
metadata:
  name: {{ include "cps-and-ncmp.fullname" . }}-service
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: cps-and-ncmp
spec:
  type: {{ .Values.cps.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "cps-and-ncmp.name" . }}
    component: cps
  ports:
    - port: {{ .Values.cps.servicePort }}
      targetPort: 8080
      nodePort: {{ .Values.cps.service.nodePort | default nil }}
