{{- if .Values.dmiStub.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cps-ncmp-dmi-stub
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: dmi-stub
spec:
  type: {{ .Values.dmiStub.service.type }}
  ports:
    - port: {{ .Values.dmiStub.service.port }}
      targetPort: {{ .Values.dmiStub.containerPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.dmiStub.service.type "NodePort") .Values.dmiStub.service.nodePort }}
      nodePort: {{ .Values.dmiStub.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "cps-and-ncmp.name" . }}
    component: dmi-stub
    instance: dmi-stub-1
{{- end }}