{{- if .Values.jaeger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cps-and-ncmp.release-name" . }}-jaeger
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cps-and-ncmp.name" . }}
      component: jaeger
  template:
    metadata:
      labels:
        app: {{ include "cps-and-ncmp.name" . }}
        component: jaeger
    spec:
      containers:
        - name: jaeger
          image: "{{ .Values.jaeger.image.repository }}:{{ .Values.jaeger.image.tag }}"
          imagePullPolicy: {{ .Values.jaeger.image.pullPolicy }}
          ports:
            - containerPort: 16686
              name: ui
            - containerPort: 14250
              name: grpc
            - containerPort: 4317
              name: otlp
          resources:
            {{- toYaml .Values.jaeger.resources | nindent 12 }}
{{- end }}
