apiVersion: v1
kind: Service
metadata:
  name: {{ include "cps-and-ncmp.release-name" . }}-kafka-service
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - name: internal
      port: {{ .Values.kafka.service.ports.internal }}
      targetPort: {{ .Values.kafka.service.ports.internal }}
    - name: external
      port: {{ .Values.kafka.service.ports.external }}
      targetPort: {{ .Values.kafka.service.ports.external }}
  selector:
    app: {{ include "cps-and-ncmp.name" . }}
    component: kafka