{{- if .Values.onapDmiStack.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cps-and-ncmp.release-name" . }}-sdnc-db
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: sdnc-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cps-and-ncmp.name" . }}
      component: sdnc-db
  template:
    metadata:
      labels:
        app: {{ include "cps-and-ncmp.name" . }}
        component: sdnc-db
    spec:
      containers:
        - name: sdnc-db
          image: "{{ .Values.onapDmiStack.sdncDb.image }}"
          ports:
            - containerPort: 3306
          env:
            {{- range $key, $value := .Values.onapDmiStack.sdncDb.env }}
            - name: {{ $key | upper }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.onapDmiStack.sdncDb.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.onapDmiStack.sdncDb.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.onapDmiStack.sdncDb.readinessProbe | nindent 12 }}
{{- end }}
