{{- if .Values.onapDmiStack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cps-and-ncmp.release-name" . }}-sdnc-certs
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: sdnc
type: Opaque
data:
  certs.properties: {{ .Files.Get "config/sdnc/certs/certs.properties" | b64enc }}
  keys0.zip: {{ .Files.Get "config/sdnc/certs/keys0.zip" | b64enc }}
{{- end }}
