apiVersion: v1
kind: Service
metadata:
  name: {{ include "cps-and-ncmp.release-name" . }}-postgres-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: postgresql
spec:
  type: NodePort
  selector:
    app: {{ include "cps-and-ncmp.name" . }}
    component: postgresql
  ports:
    - port: 9187
      targetPort: 9187
      nodePort: 30187
      protocol: TCP
