{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cps-and-ncmp.release-name" . }}-prometheus-config
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: prometheus
data:
  prometheus.yml: |
    {{- .Files.Get "config/prometheus.yml" | nindent 4 }}
{{- end }}
