#  ============LICENSE_START=======================================================
#  Copyright (C) 2025-2026 OpenInfra Foundation Europe. All rights reserved.
#  ================================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#  ============LICENSE_END=========================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cps-and-ncmp.release-name" . }}-zookeeper
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cps-and-ncmp.name" . }}
      component: zookeeper
  template:
    metadata:
      labels:
        app: {{ include "cps-and-ncmp.name" . }}
        component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.zookeeper.service.port }}
          env:
            {{- range $envName, $envValue := .Values.zookeeper.env }}
            - name: {{ $envName  | upper}}
              value: "{{ $envValue }}"
            {{- end }}
          resources:
            {{- toYaml .Values.zookeeper.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.zookeeper.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.zookeeper.readinessProbe | nindent 12 }}
