apiVersion: v1
kind: Service
metadata:
  name: {{ include "cps-and-ncmp.fullname" . }}-zookeeper
  labels:
    app: {{ include "cps-and-ncmp.name" . }}
    component: zookeeper
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - port: {{ .Values.zookeeper.service.port }}
      targetPort: {{ .Values.zookeeper.service.port }}
      protocol: TCP
      name: client
  selector:
    app: {{ include "cps-and-ncmp.name" . }}
    component: zookeeper
